version: '3.5'
services:
  app:
    restart: always
    image: finemusic
    container_name: finemusic
    build:
      context: ./
      target: dev
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3002:3000'
